#!/bin/bash

set -e
set -u

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	    CREATE USER $MS_ACCOUNTS_USER WITH PASSWORD '$MS_ACCOUNTS_PASSWORD';
	    CREATE DATABASE $MS_ACCOUNTS_DB WITH OWNER $MS_ACCOUNTS_USER;
EOSQL