tests:
  - name: "Valid Config 1"
    fileContent: |
      {"Port": "8080", "Log": "/var/log/app1.log"}
    expected:
      ServerPort: "8080"
      LogFile: "/var/log/app1.log"
      
  - name: "Valid Config 2"
    fileContent: |
      {"Port": "3000", "Log": "/tmp/app2.log"}
    expected:
      ServerPort: "3000"
      LogFile: "/tmp/app2.log"
      
  - name: "Valid Config 3"
    fileContent: |
      {"Port": "8000", "Log": "/logs/app3.log"}
    expected:
      ServerPort: "8000"
      LogFile: "/logs/app3.log"
      
  - name: "Valid Config 4"
    fileContent: |
      {"Port": "5000", "Log": "/var/log/app4.log"}
    expected:
      ServerPort: "5000"
      LogFile: "/var/log/app4.log"
      
  - name: "Valid Config 5"
    fileContent: |
      {"Port": "9000", "Log": "/tmp/app5.log"}
    expected:
      ServerPort: "9000"
      LogFile: "/tmp/app5.log"
      
  - name: "Valid Config 6"
    fileContent: |
      {"Port": "1000", "Log": "/logs/app6.log"}
    expected:
      ServerPort: "1000"
      LogFile: "/logs/app6.log"
      
  - name: "Valid Config 7"
    fileContent: |
      {"Port": "7000", "Log": "/var/log/app7.log"}
    expected:
      ServerPort: "7000"
      LogFile: "/var/log/app7.log"
      
  - name: "Valid Config 8"
    fileContent: |
      {"Port": "6000", "Log": "/tmp/app8.log"}
    expected:
      ServerPort: "6000"
      LogFile: "/tmp/app8.log"
      
  - name: "Valid Config 9"
    fileContent: |
      {"Port": "4000", "Log": "/logs/app9.log"}
    expected:
      ServerPort: "4000"
      LogFile: "/logs/app9.log"
      
  - name: "Valid Config 10"
    fileContent: |
      {"Port": "2000", "Log": "/var/log/app10.log"}
    expected:
      ServerPort: "2000"
      LogFile: "/var/log/app10.log"
      
  - name: "Valid Config 11"
    fileContent: |
      {"Port": "8081", "Log": "/var/log/app11.log"}
    expected:
      ServerPort: "8081"
      LogFile: "/var/log/app11.log"
      
  - name: "Valid Config 12"
    fileContent: |
      {"Port": "3001", "Log": "/tmp/app12.log"}
    expected:
      ServerPort: "3001"
      LogFile: "/tmp/app12.log"
      
  - name: "Valid Config 13"
    fileContent: |
      {"Port": "8001", "Log": "/logs/app13.log"}
    expected:
      ServerPort: "8001"
      LogFile: "/logs/app13.log"
      
  - name: "Valid Config 14"
    fileContent: |
      {"Port": "5001", "Log": "/var/log/app14.log"}
    expected:
      ServerPort: "5001"
      LogFile: "/var/log/app14.log"
      
  - name: "Valid Config 15"
    fileContent: |
      {"Port": "9001", "Log": "/tmp/app15.log"}
    expected:
      ServerPort: "9001"
      LogFile: "/tmp/app15.log"
      
  - name: "Valid Config 16"
    fileContent: |
      {"Port": "1001", "Log": "/logs/app16.log"}
    expected:
      ServerPort: "1001"
      LogFile: "/logs/app16.log"
      
  - name: "Valid Config 17"
    fileContent: |
      {"Port": "7001", "Log": "/var/log/app17.log"}
    expected:
      ServerPort: "7001"
      LogFile: "/var/log/app17.log"
      
  - name: "Valid Config 18"
    fileContent: |
      {"Port": "6001", "Log": "/tmp/app18.log"}
    expected:
      ServerPort: "6001"
      LogFile: "/tmp/app18.log"
      
  - name: "Valid Config 19"
    fileContent: |
      {"Port": "4001", "Log": "/logs/app19.log"}
    expected:
      ServerPort: "4001"
      LogFile: "/logs/app19.log"
      
  - name: "Valid Config 20"
    fileContent: |
      {"Port": "2001", "Log": "/var/log/app20.log"}
    expected:
      ServerPort: "2001"
      LogFile: "/var/log/app20.log"
      
  - name: "Invalid JSON Config 1"
    fileContent: |
      {"Port": "8080", "Log": "/var/log/app1.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 2"
    fileContent: |
      {"Port": "3000", "Log": "/tmp/app2.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 3"
    fileContent: |
      {"Port": "8000", "Log": "/logs/app3.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 4"
    fileContent: |
      {"Port": "5000", "Log": "/var/log/app4.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 5"
    fileContent: |
      {"Port": "9000", "Log": "/tmp/app5.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 6"
    fileContent: |
      {"Port": "1000", "Log": "/logs/app6.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 7"
    fileContent: |
      {"Port": "7000", "Log": "/var/log/app7.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 8"
    fileContent: |
      {"Port": "6000", "Log": "/tmp/app8.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 9"
    fileContent: |
      {"Port": "4000", "Log": "/logs/app9.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 10"
    fileContent: |
      {"Port": "2000", "Log": "/var/log/app10.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 11"
    fileContent: |
      {"Port": "8081", "Log": "/var/log/app11.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 12"
    fileContent: |
      {"Port": "3001", "Log": "/tmp/app12.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 13"
    fileContent: |
      {"Port": "8001", "Log": "/logs/app13.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 14"
    fileContent: |
      {"Port": "5001", "Log": "/var/log/app14.log"
    expectedError: "unable to parse config file"
    
  - name: "Invalid JSON Config 15"
    fileContent: |
      {"Port": "9001", "Log": "/tmp/app15.log"
    expectedError: "unable to parse config file"
  - name: "File Not Found 1"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 2"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 3"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 4"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 5"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 6"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 7"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 8"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 9"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 10"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 11"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 12"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 13"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 14"
    fileContent: null
    expectedError: "unable to open config file"
    
  - name: "File Not Found 15"
    fileContent: null
    expectedError: "unable to open config file"