name: CI

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - pkg/calc
          - service/auth/internal/http/handler/test
          - service/api-gateway/internal/handler/test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with: { go-version: '1.22' }

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ format('{0}', matrix.module) }}-${{ hashFiles(format('{0}/go.sum', matrix.module)) }}
          restore-keys: |
            ${{ runner.os }}-go-mod-${{ format('{0}', matrix.module) }}-

      - name: Install deps
        working-directory: ${{ matrix.module }}
        run: |
          go mod tidy
          go mod download

      - name: go vet
        working-directory: ${{ matrix.module }}
        run: go vet ./...

      - name: golangci-lint
        working-directory: ${{ matrix.module }}
        run: golangci-lint run --timeout 3m

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        module:
          - pkg/calc
          - service/auth/internal/http/handler/test
          - service/api-gateway/internal/handler/test

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with: { go-version: '1.22' }

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ format('{0}', matrix.module) }}-${{ hashFiles(format('{0}/go.sum', matrix.module)) }}
          restore-keys: |
            ${{ runner.os }}-go-mod-${{ format('{0}', matrix.module) }}-

      - name: Install deps
        working-directory: ${{ matrix.module }}
        run: |
          go mod tidy
          go mod download

      - name: Run tests
        working-directory: ${{ matrix.module }}
        run: |
          echo "=== Testing $PWD ==="
          go test -v ./... -coverprofile=coverage.out

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ${{ matrix.module }}/coverage.out
          flags: unit-${{ matrix.module }}
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}